LogicUniversityWeb/Models/DisbursementList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LogicUniversityWeb.Models
{
    public class DisbursementList
    {
        public int DisbursementID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string DepID { get; set; }
        public string DisbursementStatus { get; set; }
        public Nullable<int> OTP { get; set; }

        public string CollectionPoint { get; set; }
       
        public string Departmentname { get; set; }
        public string DateofSubmission { get; set; }
       
    }
}

LogicUniversityWeb/Controllers/DisbursementController.cs
using LogicUniversityWeb.DataBase;
using LogicUniversityWeb.EmailAlerts;
using LogicUniversityWeb.Models;
using LogicUniversityWeb.Services;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LogicUniversityWeb.Controllers
{
    [Authorize]
    public class DisbursementController : Controller
    {
        DisbursementService ds = new DisbursementService();
      
        // GET: Disbursement
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "SClerk")]

        public ActionResult createDisb()
        {
            ds.createDisbursementList();
            ds.showAllDeptName();
            return RedirectToAction("DisbursementList");
        }
        public ActionResult createDisbursement()
        {
            return View();
        }


        [Authorize(Roles = "SClerk")]
        public ActionResult DisbursementList()
        {
            List<DisbursementList> requisitionLists = ds.ShowDisbursementList();
            ViewBag.disbursementList = requisitionLists;
            return View();
        }

        [Authorize(Roles = "SSupervisor,SManager")]
        public ActionResult DisbursementListMgrSupr()
        {
            List<DisbursementList> requisitionLists = ds.ShowDisbursementList();
            ViewBag.dList = requisitionLists;
            return View();
        }

        [Authorize(Roles = "SClerk")]
        public ActionResult ViewDisbursementDetail(int id)
        {            
            List<RequisitionDetails> requisitionDetailsUserInfo = ds.ShowDisbursementDetailUserInfo(id);
            ViewBag.requisitionDetail = requisitionDetailsUserInfo;
            List<RequisitionDetails> requisitionDetailsDataInfo = ds.ShowDisbursementDetailDataInfo(id);
            ViewBag.dataInfo = requisitionDetailsDataInfo;
           
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "SClerk")]
        public ActionResult UpdateStatus(DisbursementList id)
        {
            ds.UpdateStatus(id);
            return RedirectToAction("DisbursementList");
        }

        [Authorize(Roles = "SClerk")]
        public ActionResult UpdateQuantity(List<RequisitionDetails> receivedQtyUpdate)
        {
            ds.UpdateQty(receivedQtyUpdate);
            //ds.UpdateQty(DeliveredQty, DisbursementID);
            return RedirectToAction("DisbursementList");
        }

        public int GetDisbursementID()
        {
            DisbursementList reqInfo = new DisbursementList();

            using (SqlConnection conn = new SqlConnection(DataLink.connectionString))
            {
                conn.Open();

                string cmdtext = @"select top(1) DisbursementID from DisbursementList dl,RequisitionList rl where dl.DepID=rl.DeptID_FK and rl.UserID_FK='" + (int)Session["UserID"] + "' and dl.DisbursementStatus='pending'" + " ORDER BY DisbursementID DESC";
                SqlCommand cmd = new SqlCommand(cmdtext, conn);
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read())
                {

                    reqInfo.DisbursementID = (int)reader["DisbursementID"];
                }
            }
            int DisbursementId = reqInfo.DisbursementID;
            return DisbursementId;
        }

        [Authorize(Roles = "SClerk")]
        public ActionResult RaiseDiscrepency(RequisitionDetails Db)
        {
            // ViewBag.DiscrepencyForm = Db;
            // RequisitionDetails rd = ds.getDataForDiscrepancy(id, itemID);
            // ViewBag.rQty = DeliveredQty;
            ViewData["Db"] = Db;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "SClerk")]
        public ActionResult SubmitDiscrepency(RequisitionDetails Dp)
        {
            String ItemID = Dp.ItemID;
            string StockcardID = getstockcardID(ItemID);
            string DisStatus = "PendingForApproval";

            using (SqlConnection conn = new SqlConnection(DataLink.connectionString))
            {
                conn.Open();
                string cmdtext = @"insert into Discrepancy (DisbursementID,StockCardID,DiscrepancyQty,Reason,DiscrepancyStatus,ItemID) values ('" + Dp.DisbursementID + "','" + StockcardID + "'," + Dp.DeliveredQty + ",'" + Dp.Reason + "','" + DisStatus + "','" + ItemID + "')";
                SqlCommand cmd = new SqlCommand(cmdtext, conn);
                cmd.ExecuteNonQuery();
            }

            Users u = ds.GetUserInfo((int)Session["UserID"]);
            string EmailID = u.EmailID;
            int DiscrepancyId = GetDiscrepancyID();

            SendEmailNotification send = new SendEmailNotification();

            String EmailSubject = "Request Submitted DiscrepancyID#" + DiscrepancyId;
            String EmailBody = "<p> Dear KyiPhyu,</p>";
            EmailBody += "<p>Your order is ready to deliver with Discrepancy ID" + DiscrepancyId + " for your reference.</p>";
            EmailBody += "<p>Thank you<br/>Logic University Staionery Store</p>";
            EmailBody += "<p> Please do not reply to this email it is auto-generated.</p>";

            send.SendEmailHTML("winkyiphyukyaw17@gmail.com", EmailSubject, EmailBody);

            return RedirectToAction("DisbursementList");
        }

        public string getstockcardID(string ItemID)
        {
            StockCard sc = new StockCard();
            using (SqlConnection C = new SqlConnection(DataLink.connectionString))
            {
                C.Open();
                string query = @"SELECT*from StockCard where ItemID ='" + ItemID + "'";
                SqlCommand cmd = new SqlCommand(query, C);
                ; SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    sc.ItemID = (string)reader["ItemID"];
                    sc.StockCardID = (string)reader["StockCardID"];
                }
                return sc.StockCardID; //pass to calling function (supplier controller)
            }
        }

        public int GetDiscrepancyID()
        {
            Discrepency reqInfo = new Discrepency();

            using (SqlConnection conn = new SqlConnection(DataLink.connectionString))
            {
                conn.Open();

                string cmdtext = @"  select d.DiscrepencyID
                                from DisbursementDetails dd, Discrepancy d
                                where dd.DisbursementID = d.DisbursementID and dd.ItemID = d.ItemID 
                                and d.DiscrepancyStatus='PendingForApproval'";
                SqlCommand cmd = new SqlCommand(cmdtext, conn);
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read())
                {

                    reqInfo.DiscrepencyID = (int)reader["DiscrepencyID"];
                }
            }
            int DiscrepencyID = reqInfo.DiscrepencyID;
            return DiscrepencyID;
        }       

        public ActionResult validateOTP(RequisitionDetails rd)
        {
            string OTP = ds.validateOTP(rd);
          
            RequisitionDetails userData = ds.getUserDataByDisbID(rd.DisbursementID);
            SendEmailNotification send = new SendEmailNotification();

            String EmailSubject = "Request Submitted DisbursementID#" + userData.DisbursementID;
            String EmailBody = "<p> Dear " + userData.UserName + ",</p>";
            EmailBody += "<p>Your order is ready to deliver with Disbursement ID <b>" + userData.DisbursementID + "</b> for your reference.</p>";
            EmailBody += "<p>Collection Point will be <b>" + userData.CollectionPoint + "</b></p>";
            EmailBody += "<p>" + "OTP for loging into your account is here. <b> " + OTP + " </b>." +
                " Please tell this OTP to verify your identity. "+ " </p>";
            EmailBody += "<p>Thank you<br/>Logic University Staionery Store</p>";
            EmailBody += "<p> Please do not reply to this email it is auto-generated.</p>";
            send.SendEmailHTML(userData.EmailID, EmailSubject, EmailBody);

          
            int id = rd.DisbursementID;
            return RedirectToAction("ViewDisbursementDetail/"+ id);
        }
    }
}

LogicUniversityWeb/Views/Disbursement/DisbursementList.cshtml
@model LogicUniversityWeb.Models.DisbursementList
@using LogicUniversityWeb.Models

@{
    ViewBag.Title = "DisbursementList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    <body>
        <div class="main">
            <h3><b>Disbursement List</b></h3><br />
            <table class="table  table-sm" cellspacing="0">
                <thead class="thead-dark">
                    <tr>
                        <th>Department Name</th>
                        <th>Status</th>
                        <th>Disbursement ID</th>
                        <th></th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DisbursementList r in ViewBag.disbursementList)
                    {
                        <tr>
                            @using (Html.BeginForm("UpdateStatus", "Disbursement", FormMethod.Post))
                            {
                                <td><input type="text" name="Departmentname" class="textboxx" value="@r.Departmentname"></td>
                                <td><input type="text" name="DisbursementStatus" class="textboxx" value="@r.DisbursementStatus"></td>
                                <td><input type="text" name="DisbursementID" class="textboxx" value="@r.DisbursementID" /></td>
                                <td><input type="submit" value="Delivered" class="btn btn-primary" /></td>
                                @*  <td>@r.Departmentname</td>
                                      <td>@r.DateofSubmission</td>
                                       <td>@r.DisbursementStatus</td>
                                    <td> @Html.ActionLink("Delivered", "UpdateStatus", new { id = r.DisbursementID })</td>*@
                                <td><u><font color="blue">@Html.ActionLink("Details", "ViewDisbursementDetail", new { id = r.DisbursementID }, new { @class = "btn btn-primary" })</font></u></td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </body>
}

LogicUniversityWeb/Views/Disbursement/DisbursementListMgrSupr.cshtml
@model LogicUniversityWeb.Models.DisbursementList
@using LogicUniversityWeb.Models

@{
    ViewBag.Title = "DisbursementList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    <body>
        <div class="main">
            <h3><b>Disbursement List</b></h3><br />
            <table  class="table  table-sm" cellspacing="0">
                <thead class="thead-dark">
                    <tr>
                        <th>Department Name</th>
                        @*<th>Date</th>*@
                        <th>Status</th>
                        <th>Disbursement ID</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DisbursementList r in ViewBag.dList)
                    {
                        <tr>
                            <td><input type="text" name="Departmentname" class="textboxx" value="@r.Departmentname"></td>
                            @*<td><input type="text" name="DateofSubmission" class="subDate" value="@r.DateofSubmission"></td>*@
                            <td><input type="text" name="DisbursementStatus" class="textboxx" value="@r.DisbursementStatus"></td>
                            <td><input type="text" name="DisbursementID" class="textboxx" value="@r.DisbursementID" /></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </body>
}

LogicUniversityWeb/Views/Disbursement/RaiseDiscrepency.cshtml
@model LogicUniversityWeb.Models.DisbursementDetails
@using LogicUniversityWeb.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    RequisitionDetails Db = (RequisitionDetails)ViewData["Db"];
}
@{
    <body>
        <div class="main">
            <h3><b>Raise Discrepancy</b></h3><br />
            @{
                using (Html.BeginForm("SubmitDiscrepency", "Disbursement", FormMethod.Post))
                {
                    <table id="dtBasicExample" class="table table-sm" cellspacing="0">
                        <tr>
                            <td>Disbursement ID:</td>
                            <td> <input type="text" name="DisbursementID" class="ItemNo" value="@Db.DisbursementID" readonly /></td>
                        </tr>
                        <tr>
                            <td>Item ID:</td>
                            <td><input type="text" name="itemID" class="ItemNo" value="@Db.ItemID" readonly /></td>
                        </tr>
                        <tr>
                            <td>Quantity They want:</td>
                            <td><input type="text" name="ActualQty" class="text" value="@Db.ActualQty" readonly /></td>
                        </tr>
                        <tr>
                            <td>Discrepency Quantity:</td>
                            <td><input type="text" name="DeliveredQty" class="text" value="@Db.DeliveredQty" readonly /></td>
                        </tr>
                        <tr>
                            <td>Reason:</td>
                            <td><input type="text" name="Reason" class="text" placeholder="Provide reason" /></td>
                        </tr>
                        <tr>
                            <td colspan="2" align="center">
                                <input type="submit" class="btn btn-primary" value="Submit" />
                            </td>
                        </tr>
                    </table>
                }
            }
        </div>
    </body>

}

LogicUniversityWeb/Views/Disbursement/ViewDisbursementDetail.cshtml
@model LogicUniversityWeb.Models.DisbursementDetails
@{
    ViewBag.Title = "ViewDisbursementDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var OTP = ViewBag.OTP;
}

@{
    <body>      
        <div class="main">
            <h3><b>Disbursement Detail</b></h3><br />
            @foreach (var r in ViewBag.requisitionDetail)
            {
        <form action="/Disbursement/validateOTP" method="post">
            <table class="table  table-sm" cellspacing="0">
                <tr>
                    <th>Department Name</th>
                    <td><input type="text" name="Departmentname" class="textboxx" value="@r.Departmentname" onfocus="HideBorder" /></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Collection Point</th>
                    <td><input type="text" name="CollectionPoint" class="textboxx" value="@r.CollectionPoint" onfocus="HideBorder" /></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Representative Name</th>
                    <td><input type="text" name="UserName" class="textboxx" value="@r.UserName" onfocus="HideBorder" /></td>                    
                    <td></td>
                </tr>
                <tr>
                    <th>E-mail</th>
                    <td><input type="text" name="EmailID" class="textboxx" value="@r.EmailID" onfocus="HideBorder" /></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Mobile Number</th>
                    <td><input type="text" name="MobileNo" class="textboxx" value="@r.MobileNo" onfocus="HideBorder" /></td>
                    <td><input type="text" name="DisbursementID" class="ItemID" value="@r.DisbursementID" /></td>
                </tr>
                <tr>
                    <th>OTP</th>
                    <th><input type="text"  name="OTP" class="textboxx" value="@r.OTP" onfocus="HideBorder"/></th>
                    <td><input type="submit" value="GenerateOTP" class="btn btn-primary" onclick="generateOTP(event)"/> </td>
                </tr>
            </table>
        </form>
            }

            <table id="tblUpdate" class="table  table-sm" cellspacing="0">
                <thead class="thead-dark">
                    <tr>
                        <th>Item ID</th>
                        <th>Stationery Description</th>
                        <th>Quantity</th>
                        <th>Received Quantity</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var data in ViewBag.dataInfo)
                    {
                    <tr>
                        @using (Html.BeginForm("RaiseDiscrepency", "Disbursement", FormMethod.Post))
                        {
                            <td><input type="text" name="ItemID" class="textboxx" value="@data.ItemID" onfocus="HideBorder" /></td>
                            <td><input type="text" name="ItemName" class="textboxx" value="@data.ItemName" onfocus="HideBorder" /></td>
                            <td><input type="number" name="ActualQty" class="aQty" value="@data.ActualQty" readonly /></td>
                            <td><input type="number" name="DeliveredQty" class="dQty" value="@data.DeliveredQty" min="1" max="@data.ActualQty" /></td>
                            <td><input type="submit" value="CreateDiscrepancy" class="btn btn-primary" /></td>
                            <td><input type="text" name="DisbursementID" class="ItemID" value="@data.DisbursementID" /></td>
                            <td><input type="text" name="DisbursementStatus" class="ItemID" value="@data.DisbursementStatus" /></td>
                        }
                    </tr>
                    }
                </tbody>
            </table>
            <input type="button" class="btn btn-primary" id="btnUpdate" value="Update Qty" onclick="alertFun(event)"/>
        </div>
        @* }*@
    </body>
}

<script src="~/Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>
<script type="text/javascript">

    $("body").on("click", "#btnUpdate", function () {
        //Loop through the Table rows and build a JSON array.
        var receivedQtyUpdate = new Array();
        $("#tblUpdate TBODY TR").each(function () {
            var row = $(this);
            var qtyUpdate = {};
            qtyUpdate.ItemID = row.find("td:eq(0) input[type='text']").val();
            qtyUpdate.ItemName = row.find("td:eq(1) input[type='text']").val();
            qtyUpdate.ActualQty = row.find("td:eq(2) input[type='number']").val();
            qtyUpdate.DeliveredQty = row.find("td:eq(3) input[type='number']").val();
            qtyUpdate.DisbursementID = row.find("td:eq(5) input[type='text']").val();
            receivedQtyUpdate.push(qtyUpdate);
        });

        //Send the JSON array to Controller using AJAX.
        $.ajax({
            type: "POST",
            url: "/Disbursement/UpdateQuantity",
            data: JSON.stringify(receivedQtyUpdate),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (r) {
                alert(r + " record(s) inserted.");
            }
        });
    });

    function alertFun(event) {
        alert("Already Updated")
    }
    function generateOTP(event) {
        alert("OTP has been generated")
    }

     $(document).ready(function () {
        $("#tblUpdate TBODY TR").each(function () {
            var row = $(this);
            BtnStatus = row.find("td:eq(6) input[type='text']").val();


            if (BtnStatus == 'delivered') {
                $("#btnUpdate").hide();
            }
        });
    });

</script>

LogicUniversityWeb/Views/Disbursement/createDisbursement.cshtml
@{
    ViewBag.Title = "createDisbursement";
}


@using (Html.BeginForm("createDisb", "Disbursement", FormMethod.Post))
{
    <div align="center">
        <input type="submit" class="btn btn-primary " value="CreateDisbursement" />
    </div>
  }

  